Health Information System/Controllers/_AddressController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Health_Information_System.HIS.DAL;
using Health_Information_System.Models;

namespace Health_Information_System.Controllers
{
    public class _AddressController : Controller
    {
        private HISDBContext db = new HISDBContext();

        // GET: _Address
        public ActionResult Index()
        {
            var addresses = db.Addresses.Include(a => a.Cities);
            return View(addresses.ToList());
        }

        [ChildActionOnly]
        public ViewResult _Address(Models.Members model)
        {
            Addresses addresses = db.Addresses.Include(a => a.Cities).FirstOrDefault(a => a.OwnerTypeID == OwnerType.Member & a.OwnerID == model.ID);
            ViewBag.CityID = new SelectList(db.Cities, "CityID", "Name");
            ViewBag.MemberID = model.ID;
            return View(addresses);
        }

        [ChildActionOnly]
        public ViewResult _CompanyAddress(Models.Companies model)
        {
            Addresses addresses = db.Addresses.Include(a => a.Cities).FirstOrDefault(a => a.OwnerTypeID == OwnerType.Company & a.OwnerID == model.CompanyID);
            return View(addresses);
        }

        // GET: _Address/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Addresses addresses = db.Addresses.Find(id);
            if (addresses == null)
            {
                return HttpNotFound();
            }
            return View(addresses);
        }

        // GET: _Address/Create
        public ActionResult Create()
        {
            ViewBag.CityID = new SelectList(db.Cities, "CityID", "Name");
            return View("Members");
        }

        // POST: _Address/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "AddressID,OwnerTypeID,OwnerID,Email1,Email2,ContactPerson,AddressLine1,AddressLine2,CityID,WorkTelephone,ContactPersonTelephone,IsPrimary,CreatedBy,CreatedDate,UpdatedBy,UpdatedDate")] Addresses addresses)
        {
            if (ModelState.IsValid)
            {
                db.Addresses.Add(addresses);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CityID = new SelectList(db.Cities, "CityID", "Name", addresses.CityID);
            return View(addresses);
        }

        public ActionResult Create([Bind(Include = "AddressID,OwnerTypeID,OwnerID,Email1,Email2,ContactPerson,AddressLine1,AddressLine2,CityID,WorkTelephone,ContactPersonTelephone,IsPrimary,CreatedBy,CreatedDate,UpdatedBy,UpdatedDate")] Addresses addresses, Models.Members Members)
        {
            if (ModelState.IsValid)
            {
                addresses.OwnerID = ViewBag.MemberID;
                addresses.OwnerTypeID = OwnerType.Member;
                db.Addresses.Add(addresses);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CityID = new SelectList(db.Cities, "CityID", "Name", addresses.CityID);
            return View(addresses);
        }

        // GET: _Address/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Addresses addresses = db.Addresses.Find(id);
            if (addresses == null)
            {
                return HttpNotFound();
            }
            ViewBag.CityID = new SelectList(db.Cities, "CityID", "Name", addresses.CityID);
            return View(addresses);
        }

        // POST: _Address/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "AddressID,OwnerTypeID,OwnerID,Email1,Email2,ContactPerson,AddressLine1,AddressLine2,CityID,WorkTelephone,ContactPersonTelephone,IsPrimary,CreatedBy,CreatedDate,UpdatedBy,UpdatedDate")] Addresses addresses)
        {
            if (ModelState.IsValid)
            {
                db.Entry(addresses).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CityID = new SelectList(db.Cities, "CityID", "Name", addresses.CityID);
            return View(addresses);
        }

        // GET: _Address/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Addresses addresses = db.Addresses.Find(id);
            if (addresses == null)
            {
                return HttpNotFound();
            }
            return View(addresses);
        }

        // POST: _Address/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Addresses addresses = db.Addresses.Find(id);
            db.Addresses.Remove(addresses);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Health Information System/Views/Shared/_Address.cshtml
@model Health_Information_System.Models.Addresses


@using (Html.BeginForm()) 
{

    <div class="form-horizontal">
        <div class="col-sm-10">
            <div class="row">
                <div class="form-group col-sm-5">
                    @Html.LabelFor(model => model.AddressLine1, htmlAttributes: new { @class = "control-label" })
                    @Html.EditorFor(model => model.AddressLine1, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.AddressLine1, "", new { @class = "text-danger" })
                </div>

                <div class="form-group col-sm-5">
                    @Html.LabelFor(model => model.AddressLine2, htmlAttributes: new { @class = "control-label" })
                    @Html.EditorFor(model => model.AddressLine2, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.AddressLine2, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>


        <div class="col-sm-10">
            <div class="row">
                <div class="form-group col-sm-5">
                    @Html.LabelFor(model => model.Email1, htmlAttributes: new { @class = "control-label" })
                    @Html.EditorFor(model => model.Email1, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email1, "", new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Email2, htmlAttributes: new { @class = "control-label" })
                    @Html.EditorFor(model => model.Email2, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email2, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="col-sm-10">
            <div class="row">
                <div class="form-group col-sm-5">
                    @Html.LabelFor(model => model.ContactPerson, htmlAttributes: new { @class = "control-label" })
                    @Html.EditorFor(model => model.ContactPerson, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ContactPerson, "", new { @class = "text-danger" })
                </div>

                <div class="form-group col-sm-5">
                    @Html.LabelFor(model => model.CityID, htmlAttributes: new { @class = "control-label" })
                    @Html.DropDownList("CityID", null,  htmlAttributes : new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.CityID, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="col-sm-10">
            <div class="row">
                <div class="form-group col-sm-5">
                    @Html.LabelFor(model => model.WorkTelephone, htmlAttributes: new { @class = "control-label" })
                    @Html.EditorFor(model => model.WorkTelephone, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.WorkTelephone, "", new { @class = "text-danger" })
                </div>

                <div class="form-group col-sm-5">
                    @Html.LabelFor(model => model.ContactPersonTelephone, htmlAttributes: new { @class = "control-label" })
                    @Html.EditorFor(model => model.ContactPersonTelephone, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ContactPersonTelephone, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-5">
                <input type="button" value="Create" class="btn btn-default" onclick="location.href='@Url.Action("Create", "_Address")'"/>
            </div>
        </div>
    </div>
}


            @section Scripts {
                @Scripts.Render("~/bundles/jqueryval")
            }

Health Information System/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Health Information System</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Health Information System", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container-fluid body-content">
        @RenderBody()        
    </div>
    <div class="row text-center margin-top-10">
        <hr style="width:60%"/>
        <footer>
            <p>&copy; @DateTime.Now.Year - HIS</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Health Information System/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Health Information System</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Health Information System", "Index", "Home", new { area = "" }, new { @class = "navbar-brand", @style = "font-size:1.5em;font-family:'Lucida Sans Unicode', 'Lucida Grande', sans-serif" })
            </div>
        </div>
    </div>
    <div class="container body-content">
          @RenderBody()
        <br />
        <hr />
        <footer class="text-center">
            <p>&copy; @DateTime.Now.Year - HIS - Vault ITS</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Health Information System/Views/Shared/_MemberLayout.cshtml
<!DOCTYPE html>
@{ 
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div class="col-md-12">
        <div class="row">
            <div class="col-md-2 margin-top-10">
                <div class="row">
                    <div class="col-xs-6 col-md-10">
                        <a href="#" class="thumbnail">
                            <img src="~/Images/Thumbnail.png" alt="...">
                        </a>
                    </div>
                </div>
                <ul class="nav nav-pills nav-stacked">
                    <li role="presentation" class="active"><a href="#">Member</a></li>
                    <li role="presentation"><a href="#">Approve</a></li>
                    <li role="presentation" class="danger"><a href="#">Delete</a></li>
                    <li role="presentation" class="active"><a href="#">Accounts</a></li>
                    <li role="presentation"><a href="#">View Accounts</a></li>
                </ul>
            </div>
            <div class="col-md-8 col-md-offset-1">
                @RenderBody()
            </div><br />
        </div>
    </div>
    @RenderSection("scripts", required: false)
</body>
</html>